### ISSUE TITLE
RUNC troubleshooting documentation request

### ISSUE THREAD

**Issue by GibliX** [kubescape/node-agent#138]
Add troubleshooting documentation for RUNC issues on helm install.

Suggested solution
- Locate the path where the runc binary in your cluster using `which runc` for instance
- Set the following environment variable when running the helm install command `--set nodeAgent.env[0].name=<RUNC_PATH>,nodeAgent.env[0].value=/run/runc`

**Comment by alegrey91** [comment]
we are probably moving this section into a different repository since it will be more appropriate
